_wandb:
    value:
        cli_version: 0.27.2
        e:
            6c872akh9ur2ga4ktiokaeixbnob4vho:
                codePath: /home/aditya29f70/smart_mcq_solver_challenge_iitm_dl_genai_proj/notebooks/milestone-0.ipynb
                codePathLocal: milestone-0.ipynb
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1081101176832"
                        used: "53392130048"
                email: 24f2002970@ds.study.iitm.ac.in
                executable: /home/aditya29f70/smart_mcq_solver_challenge_iitm_dl_genai_proj/venv/bin/python
                git:
                    commit: 4483fa3fabed710787149c0c466fef1ae64c96a1
                    remote: https://github.com/24f2002970/Smart-MCQ-Solver-Challenge-24F2002970.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-ac8522e2-633d-bed4-eb05-826aed25a80a
                host: LAPTOP-G8QOT8MJ
                memory:
                    total: "12395376640"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/aditya29f70/smart_mcq_solver_challenge_iitm_dl_genai_proj/notebooks/milestone-0.ipynb
                python: CPython 3.10.12
                root: /home/aditya29f70/smart_mcq_solver_challenge_iitm_dl_genai_proj/notebooks
                startedAt: "2026-06-08T12:48:45.086101Z"
                writerId: 6c872akh9ur2ga4ktiokaeixbnob4vho
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.12
            "5": 0.27.2
            "8":
                - 1
            "12": 0.27.2
            "13": linux-x86_64
architecture:
    value: distilbert
batch_size:
    value: 16
epochs:
    value: 1
number of levels:
    value: 2
